### ISSUE TITLE
How to get the Figure 11 in the paper?

### ISSUE THREAD

**Issue by star-journey** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#11]
Hello, 

Thank you for this great work.
I am very interested in Figure 11 of your paper, as the images appear very realistic. Could you please provide a detailed explanation of how these images were synthesized? It would be even more helpful if you could share some of the code used in the process. 

![image](https://user-images.githubusercontent.com/13918778/119441726-74e5a980-bcdb-11eb-8d55-55b3e2c5f7be.png)
![image](https://user-images.githubusercontent.com/13918778/119441933-cee66f00-bcdb-11eb-907e-776ed1f47054.png)
![image](https://user-images.githubusercontent.com/13918778/119442075-09e8a280-bcdc-11eb-826a-cf8277f3c7cc.png)

Thank you.

**Comment by Utkarsh-Deshmukh** [comment]
these are synthetically generated. I used the ones provided in the paper, but if you were to generate these yourself, you can do this using various blur operators such as gaussian, median, motion-blur, radial-blur etc.
You can use a mask to mask out some area to not be blurred which you can use for evaluating the blur-detector's performance

**Comment by star-journey** [comment]
Do you mean to first blur the image, then use a mask to select a specific area of the clear image, and finally composite the blurred parts with the clear area by the mask?

**Comment by Utkarsh-Deshmukh** [comment]
yes

**Comment by star-journey** [comment]
Thank you for the quick response. It is helpful to me.
