### ISSUE TITLE
Deblurring using the blur map

### ISSUE THREAD

**Issue by lmmx** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#2]
The second half of the task achieved in the original paper was to perform deblurring using the MATLAB code from [Spatially-Varying Out-Of-Focus Image Deblurring with L1-2 Optimization and a Guided Blur Map,](https://homepage.iis.sinica.edu.tw/~ctshen/) however this is no longer available online...

Is there an alternative deblurring tool the blur map can be used as input for if this is no longer available to port to Python?

**Comment by Utkarsh-Deshmukh** [comment]
you may find the matlab codes for that paper here:
https://homepage.iis.sinica.edu.tw/~ctshen/svDeblur/svDeblur.html

I have not done any in depth study on how to accomplish the image deblurring task so I may not be the right person to say what other viable alternatives are available.
