### ISSUE TITLE
Conflict with scikit-image

### ISSUE THREAD

**Issue by Karol-G** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#3]
Hi,

I tried using your package, but it seems there is a version conflict with scikit-image. If I install blur-detector then I cannot use scikit-image anymore and vice versa. Are you aware of this issue and do you know how to solve it?

Best,
Karol

**Comment by Utkarsh-Deshmukh** [comment]
Sorry for the late reply. Is this still an issue? Can you try upgrading the scikit-image module after installing the blur detector?
