### ISSUE TITLE
Black output

### ISSUE THREAD

**Issue by Riretta** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#4]
Hi!
I am trying your repository but to me, it always results in black images doesn't matter if the image has focus things or not.

I did:
    img = cv2.imread('motion0138.jpg', 0)
    blur_detector = BlurDetector(downsampling_factor=4, num_scales=3, scale_start=2, entropy_filt_kernel_sze=7, sigma_s_RF_filter=15, sigma_r_RF_filter=0.25, num_iterations_RF_filter=3)

    map = blur_detector.detectBlur(img)
    print(map/np.max(map))
    cv2.imwrite('a.jpg', img)
    cv2.imwrite('b.jpg', map/np.max(map))

Am I doing something wrong?

**Comment by Utkarsh-Deshmukh** [comment]
Can you please share the image so that i can try to recreate the issue on my end?

**Comment by Blade6570** [comment]
> Hi! I am trying your repository but to me, it always results in black images doesn't matter if the image has focus things or not.
> 
> I did: img = cv2.imread('motion0138.jpg', 0) blur_detector = BlurDetector(downsampling_factor=4, num_scales=3, scale_start=2, entropy_filt_kernel_sze=7, sigma_s_RF_filter=15, sigma_r_RF_filter=0.25, num_iterations_RF_filter=3)
> 
> ```
> map = blur_detector.detectBlur(img)
> print(map/np.max(map))
> cv2.imwrite('a.jpg', img)
> cv2.imwrite('b.jpg', map/np.max(map))
> ```
> 
> Am I doing something wrong?

Yes, the map is in between 0 to 1. So, multiply 255 before saving it.

**Comment by Utkarsh-Deshmukh** [comment]
So, you were able to save the map? Is it safe to close this issue?
