### ISSUE TITLE
Disable output

### ISSUE THREAD

**Issue by gizarchik** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#5]
It would be great if there will be a flag to disable output.

Now I am forced to use statement `with io.capture_output() as captured:' to solve this problem in jupyter notebook. In a file script, you usually have to do more complicated ways.

**Comment by Utkarsh-Deshmukh** [comment]
The Blur Detector object by itself is not programmed to show the output image during every run. In the example.py file, i am using cv2.imshow() to display the output. Are you sure you are running your codes without this so as to not display the image by default?

**Comment by gizarchik** [comment]
Oh, sorry for the ambiguity. I meant progress output.
In the source code this can be seen in the function: https://github.com/Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python/blob/8c8a35b51169ff588b8dd145f8a9a6c7d1bfbb01/BlurDetector.py#L32-L50

**Comment by Utkarsh-Deshmukh** [comment]
ohh i see your point now..
I have pushed a new change which fixes this. When you call the constructor, you can set the `show_progress` flag to `False`
Please see the example to gain clarity
