### ISSUE TITLE
UserWarning

### ISSUE THREAD

**Issue by Fedya2006** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#6]
Can't run your project, same error every time: /.../venv/lib/python3.6/site-packages/blur_detector/__init__.py:243:UserWarning: Possible precision loss converting image of type float64 to uint8 as required by rank filters. Convert manually using skimage.util.img_as_ubyte to silence this warning. 
local_entropy = self.entropyFilt(T_max).
  
Used your code in README.

**Comment by Utkarsh-Deshmukh** [comment]
@Fedya2006 can you provide me the image that you are using so that I can try to run it on that and try and recreate the issue on my end?

**Comment by Fedya2006** [comment]
![razmytaya-gorodskaya-fotografiya-s-mashinami](https://user-images.githubusercontent.com/90349792/216681709-5cce56ce-bec7-4e43-ba99-2ac3f72d98ec.jpg)

**Comment by Fedya2006** [comment]
> @Fedya2006 can you provide me the image that you are using so that I can try to run it on that and try and recreate the issue on my end?
![razmytaya-gorodskaya-fotografiya-s-mashinami](https://user-images.githubusercontent.com/90349792/216681846-b1f12603-bd0c-4b6c-bae3-774ee6a05a71.jpg)

**Comment by Fedya2006** [comment]
@Utkarsh-Deshmukh Can you write a version of your python and opencv?

**Comment by Utkarsh-Deshmukh** [comment]
thats interesting.. I was able to generate the output. My python is 3.10.9
Can you try upgrading your python?

**Comment by Utkarsh-Deshmukh** [comment]
my opencv version is 4.7.0

**Comment by Fedya2006** [comment]
sorry my fault
