### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by gautier-laurent** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#7]
Dear Utkarsh,

Thank you for this algorithm.
I am looking at using it for masking blurred part of pictures as a preprocessing for photogrammetry.

Could you provide some elements of documentation for the parameters of the API function?
My test with the parameters as in the examples were promising, but giving a smooth delineation of the blurred region.
For my application I really what to avoid including any blurred area.
I tried changing the downsampling factor and other parameters, which seems to fit more to my expectations,
but I am not entirely sure to understand the effect of those parameters.

Would you have any recommendations as how to improve the results in that case?

Best regards

Gautier Laurent

**Comment by Utkarsh-Deshmukh** [comment]
Hi Gautier Laurent,
The way this algorithm works is that it computes the DCT any location on the image at various scales. These DCT coefficients are separated into high frequency and low frequency coefficients and the low frequency coefficients are discarded.

The high frequency coefficients at various scales are fused together and the maximum is selected.

this is computed at various locations of the image to form the high frequency energy map. The coarse blur detection output is computed by using an entropy filter on top of this energy map.
This coarse map is fine tuned using a Transform Domain recursive filter.

Here are the input tunable parameters:
```
1) downsampling_factor --> this controls the jumpsize between pixels. if this value is 1, it means the computations happen on every pixel, if this value is 2, it means that the computations happen on every alternate pixel
2) num_scales --> this controls the number of scales on which the blur is to be detected
3) scale_start --> the value of the first scale is given as (2^(scale_start)) - 1; so if the scale_start is given as 3, the size of the first window would be 7x7 pixels
4) entropy_filt_kernel_sze --> this is the kernel size for the entropy filter
5) sigma_s_RF_filter --> this parameter controls the smoothing of the Transform domain recursive filter
6) sigma_r_RF_filter --> this parameter controls the smoothing of the Transform domain recursive filter
7) num_iterations_RF_filter --> this parameter controls the number of iterations that are performed to smooth the energy map in the Transform Domain Recursive Filter

**Comment by karthikdattay** [comment]
Hey utkarsh, when I run it on my images, I get a blank black image, I guess the threshold is too high. How do I set this? my entire image isnt blur.
