### ISSUE TITLE
Error while installing blue_detector on windows

### ISSUE THREAD

**Issue by apanand14** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#8]
Hello,

I would like to install blue_detector on windows but somehow installation is not able to complete and provides me os error. I'm not sure that does it work on windows or not?. Your help will be appreciated. Thank you.

**Comment by Utkarsh-Deshmukh** [comment]
it should work on windows. i imagine you are doing a pip install, is that right?

**Comment by Utkarsh-Deshmukh** [comment]
can you verify the pip version, and make sure it is up to date?

**Comment by apanand14** [comment]
Thank you for the response but I'm getting this error:

`C:\Developer>pip install blur_detector
Collecting blur_detector
  Using cached blur-detector-0.0.6.tar.gz (5.9 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in c:\users\appdata\local\programs\python\python39-32\lib\site-packages (from blur_detector) (1.24.3)
Requirement already satisfied: opencv-python in c:\users\appdata\local\programs\python\python39-32\lib\site-packages (from blur_detector) (4.7.0.72)
Collecting scipy (from blur_detector)
  Using cached scipy-1.11.1.tar.gz (56.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      + meson setup C:\Users\AppData\Local\Temp\pip-install-9cgi2w6r\scipy_a302516d1f184530b35aae6a1baa0ae9 C:\Users\topseven\AppData\Local\Temp\pip-install-9cgi2w6r\scipy_a302516d1f184530b35aae6a1baa0ae9\.mesonpy-yi7jwnyh\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users
\topseven\AppData\Local\Temp\pip-install-9cgi2w6r\scipy_a302516d1f184530b35aae6a1baa0ae9\.mesonpy-yi7jwnyh\build\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.0
      Source dir: C:\Users\AppData\Local\Temp\pip-install-9cgi2w6r\scipy_a302516d1f184530b35aae6a1baa0ae9
      Build dir: C:\Users\AppData\Local\Temp\pip-install-9cgi2w6r\scipy_a302516d1f184530b35aae6a1baa0ae9\.mesonpy-yi7jwnyh\build
      Build type: native build
      Project name: SciPy
      Project version: 1.11.1
     
      ..\..\meson.build:1:0: ERROR: Compiler cl cannot compile programs.
     
      A full log can be found at C:\Users\AppData\Local\Temp\pip-install-9cgi2w6r\scipy_a302516d1f184530b35aae6a1baa0ae9\.mesonpy-yi7jwnyh\build\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by Utkarsh-Deshmukh** [comment]
try downgrading your pip.
Try something like this: `pip install pip==21.3.1`

**Comment by apanand14** [comment]
Thank you for the quick response. I had also problem of Pillow version due to python 3.9. I created another enviornment with 3.8 and installation works fine. But when I run the sample code I get the error:

`C:\Users\anaconda3\envs\temp\python.exe C:/Developer/blurdetection/blur_check.py
Traceback (most recent call last):
  File "C:/Developer/blurdetection/blur_check.py", line 12, in <module>
    blur_map = blur_detector.detectBlur(img, downsampling_factor=4, num_scales=4, scale_start=2, num_iterations_RF_filter=3)
  File "C:\Users\temp\lib\site-packages\blur_detector\__init__.py", line 264, in detectBlur
    return(blur_detector_object.detectBlur(img))
  File "C:\Users\temp\lib\site-packages\blur_detector\__init__.py", line 172, in detectBlur
    ori_rows, ori_cols = np.shape(img)
ValueError: too many values to unpack (expected 2)`

**Comment by apanand14** [comment]
Sorry for trouble. Works fine everything. I will contact you if something doesn't work as expected. thank you for the implemenation. Great work.

**Comment by Utkarsh-Deshmukh** [comment]
could you write what was the problem, so that it will be helpful to others who might have the same issue.
Please give a brief description about what the problem was, and what did you do to solve it. Thank you
