### ISSUE TITLE
How to get a blur extent number from 0 to 1?

### ISSUE THREAD

**Issue by preethamam** [Utkarsh-Deshmukh/Spatially-Varying-Blur-Detection-python#9]
Is there a way to measure the blur extent value from 0 to 1? Zero corresponds to no/small blur and 1 is the maximum blur.

**Comment by Utkarsh-Deshmukh** [comment]
this library outputs a segmentation map to indicate the location of the blur and also the amount of it. you might have to convert this map into a scalar to give an objective score (normalized to 0-1) for the entire image.
